### ISSUE TITLE
[Bug]: failed to exit by ctrl + c after modifying _meta.json

### ISSUE THREAD

**Issue by yuyutaotao** [web-infra-dev/rspress#1209]
### Version

```sh
System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M3 Pro
    Memory: 5.88 GB / 36.00 GB
    Shell: 3.2.57 - /bin/bash
  Browsers:
    Chrome: 126.0.6478.116
    Safari: 17.3
  npmPackages:
    rspress: ^1.24.0 => 1.25.0
```

### Details

![CleanShot 2024-06-26 at 10 13 58@2x](https://github.com/web-infra-dev/rspress/assets/167746126/4c4bc497-d866-4e4e-be79-b96c835e5ba6)

### Reproduce link

-

### Reproduce Steps

* modify _meta.json
* hit `ctrl + c`

**Comment by Timeless0911** [comment]
This issue seems not to be reproduced stably, I tried several times, and can't reproduce it. 

I guess it is related to 
https://github.com/web-infra-dev/rspress/blob/54be7c8b9176bcd92a393289fe5eee88540c744b/packages/cli/src/index.ts#L76-L107, graceful shutdown is something more complicated than we think.

**Comment by Timeless0911** [comment]
When we modify `_meta.json` or shutdown using ctrl + c, the dev server will be restarted, including the steps of restarting webpack dev middleware. When the project's node_modules is too large, there is a problem that the close time is particularly long in watchpack maybe.

We can config in `rspress.config` like below

```ts
builderConfig: {
  tools: {
    rspack: {
      watchOptions: {
        ignored: /node_modules/,
      },
    },
  },
},
```

see https://www.rspack.dev/config/watch#watchoptions
