### ISSUE TITLE
[Bug]: `docs/public/**/*.js` was mistakenly regarded as a route

### ISSUE THREAD

**Issue by Liu7i-67** [web-infra-dev/rspress#1291]
### 版本信息

```sh
本地信息：
  System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12500
    Memory: 15.27 GB / 31.70 GB
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.1


codesandbox的信息
System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 2.20 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  npmPackages:
    rspress: ^1.0.0 => 1.6.2
```

### 问题详情

![Snipaste_2024-07-31_16-25-26](https://github.com/user-attachments/assets/08761f52-30d0-4847-b49c-d77ac56e6648)

- 使用`pnpm create rspress@latest`创建的项目
- 运行`pnpm build`

> 静态资源目录下的html文件没有被复制到产物中  
> 并且html目录下的所有js都被编译成了html文件生成到了产物中

 page文件夹作为html文件夹的对照成功的生成到了产物中  
但是page文件夹中的js文件也被编译成了html文件生成到了产物中
 

### 复现链接

https://codesandbox.io/p/devbox/beautiful-clarke-x43xvz?workspaceId=fb769fab-1d81-4b5d-bcbf-985898f418ac

### 复现步骤

[rs_test.zip](https://github.com/user-attachments/files/16438526/rs_test.zip)

下载此demo，安装依赖后进行构建 
或者在复现链接直接构建

**Comment by SoonIter** [comment]
your folder name `html` is conflicted so that the output is strange

You can use other names, eg: "heybro"

<img width="225" alt="image" src="https://github.com/user-attachments/assets/0b3f91cb-eb48-43bc-9e18-9c97d6b113ca">

`.js` files in publicDir was mistakenly regarded as a route, so the html file was generated through ssg  and `doc_build/public/heybro/hello1111.html` is generated  which is a bug of `@rspress/plugin-auto-nav`

**Comment by Liu7i-67** [comment]
Okay, I'll try to fix it

Soon ***@***.***> 于2024年7月31日周三 17:29写道：

**Comment by Liu7i-67** [comment]
[image: image.png]
***@***.***/plugin-auto-nav插件没有关系
我在walk处阻断了对public目录的进一步处理，但是错误仍然在继续

qi liu ***@***.***> 于2024年7月31日周三 17:43写道：

**Comment by Liu7i-67** [comment]
我找到了其他方案，写一个新插件在构建完成后去移除多余的public并将我需要的html文件复制到产物中。
虽然构建时的报错有点让人揪心，但是我拿到了我想要的产物，哈哈
[image: image.png]

qi liu ***@***.***> 于2024年8月1日周四 09:38写道：
