### ISSUE TITLE
[Bug]: Anchor is removed after redirection

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspress#154]
### Version

```sh
-
```

### Details

When an English user visits https://modernjs.dev/builder/api/config-html.html#htmldisablehtmlfolder, the URL will be redirected to https://modernjs.dev/builder/en/api/config-html.html, and the hash anchor is removed.

The hash anchor may be the same between the English and Chinese documentation, so it is better to keep the hash anchor.

### Reproduce link

https://modernjs.dev/builder/api/config-html.html#htmldisablehtmlfolder

### Reproduce Steps

See above.

**Comment by zoolsher** [comment]
I'll fix this

**Comment by zoolsher** [comment]
I didn't find a good way to fix this and I looked into the community it seems to be a common issue.

The reason is the anchor in Chinese and english are not the same and it happens to be the same in this case(both #htmldisablehtmlfolder). Vue website have the same issue. 

If we simply add the anchor to the link, would it be confusing that the anchor only works sometime?

**Comment by chenjiahan** [comment]
> If we simply add the anchor to the link, would it be confusing that the anchor only works sometime?

Sometimes it's just a useless anchor, it's fine because it does not break anything..

**Comment by zoolsher** [comment]
But I believe some of the community would prefer a clean url 😄

**Comment by chenjiahan** [comment]
That's true 😂

**Comment by sanyuan0704** [comment]
I think the anchor can be reserved to make the experience in some cases better.

**Comment by sanyuan0704** [comment]
The hash is computed from markdown/mdx title so we cannot ensure the hash is consistent between different languages. But from the perspective of framework, we can keep the same experience as much as possible, although not 100% accurate.
