### ISSUE TITLE
[Feature]: Add shiki syntax highlighting plugin support

### ISSUE THREAD

**Issue by hustcer** [web-infra-dev/rspress#211]
### What problem does this feature solve?

`rspress` seems to support PL syntax highlighting by prismjs at the moment, hopefully the [`Shiki`](https://github.com/shikijs/shiki) plugin can be added as well. The advantage of supporting `shiki` is that prism may can't support syntax highlighting for some less common programming languages in the short term, but if it supports the `shiki` plugin, the corresponding syntax highlighting grammar can be applied to `shiki` as long as it has a VSCode extension. And the [Nushell official site](https://www.nushell.sh/book/cheat_sheet.html) is currently using this solution!

### What does the proposed API look like?

Something like this： https://vuepress.github.io/reference/plugin/shiki.html

**Comment by hustcer** [comment]
Hey, any thoughts on this issue?
We may move away from `VuePress` and use `rspress` instead someday: https://github.com/nushell/nushell.github.io/issues/1126
And this is the most important thing we care about. Thanks

**Comment by sanyuan0704** [comment]
Thanks for feedback. I think it's important to ensure the flexibility in code highlight solution. Currently the most difficult thing  is that rspress does code highlight in runtime instead of compiled-time, in the meanwhile, shiki only supports compiled-time code highlight in most cases. So i'm going to solve the problem and add a @rspress/plugin-shiki to support shiki highlight in rspress.

**Comment by hustcer** [comment]
That’s great, very appreciated !

**Comment by sanyuan0704** [comment]
I will support the plugin this week and notify you after finishing it.

**Comment by hustcer** [comment]
Take it easy, no rush at all

**Comment by sanyuan0704** [comment]
https://rspress.dev/zh/plugin/official-plugins/shiki.html

**Comment by hustcer** [comment]
@sanyuan0704 Great, Thanks
